sudo: false
language: java
jdk:
- oraclejdk8
services:
- redis-server
script:
- test/run.sh
notifications:
  slack:
    secure: a6JJyUmpCDy/I7X6b7mHIV8WkuzRYnpvjzESXfSLmstl+yhTplnM/uCiQdxvQqjoSrIoPDGw1rwmnK3DwR4+U+dFIxoY3HFwEKhPvZJa13PfqSVqly4Lixe4xbknshyoJAea/rIr94RntTMij7ftnX6F7nXhR2VDNCAnPBisPG0=
