name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: spring-guides/getting-started-macros/.github/workflows/build_initial_complete_maven_gradle.yml@main